# ====================================================================
# Выделение памяти под виртуальную машину GitHub Actions (16 ГБ RAM)
# ====================================================================
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Максимальное распараллеливание на 4 ядрах runner
org.gradle.workers.max=4

# Параллельная сборка задач
org.gradle.parallel=true

# Локальный сборочный кэш (построчный хэш исходников)
org.gradle.caching=true

# Кэширование графа конфигурации
org.gradle.configuration-cache=true

# На CI не тратим такты процессора на слежение за изменениями файлов
org.gradle.vfs.watch=false

# ====================================================================
# Настройки Android Gradle Plugin (AGP 9.x)
# ====================================================================
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.experimental.disableCompileSdkChecks=true

# ====================================================================
# Настройки компилятора Kotlin 2.4.x
# ====================================================================
kotlin.code.style=official
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8